import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import TextInput from '../components/TextInput';
import AnalysisResults from '../components/AnalysisResults';

// Programmatic SEO Database
const pSEODatabase = {
  'chatgpt-watermark-remover': {
    title: 'ChatGPT Watermark Remover | Bypass AI Detection',
    description: 'Remove hidden watermarks from ChatGPT text. Evade AI detection with our advanced restructuring algorithm.',
    h1: 'ChatGPT Watermark Remover',
    toolType: 'remover',
    platform: 'ChatGPT'
  },
  'turnitin-ai-detector-bypass': {
    title: 'Bypass Turnitin AI Detector | Humanize AI Text',
    description: 'Learn how to bypass Turnitin AI detection. Our tool humanizes AI text to pass Turnitin seamlessly.',
    h1: 'Bypass Turnitin AI Detector',
    toolType: 'remover',
    platform: 'Turnitin'
  },
  'gemini-text-humanizer': {
    title: 'Gemini Text Humanizer | Remove AI Footprints',
    description: 'Humanize text generated by Google Gemini. Remove AI footprints and watermarks instantly.',
    h1: 'Gemini Text Humanizer',
    toolType: 'remover',
    platform: 'Gemini'
  },
  'claude-3-5-sonnet-watermark-removal': {
    title: 'Claude 3.5 Sonnet Watermark Removal Tool',
    description: 'Detect and remove statistical watermarks from Claude 3.5 Sonnet outputs.',
    h1: 'Claude 3.5 Sonnet Watermark Removal',
    toolType: 'remover',
    platform: 'Claude 3.5 Sonnet'
  },
  'openai-text-detector': {
    title: 'OpenAI Text Detector | Check for AI Generation',
    description: 'Detect if text was written by OpenAI models. Accurate statistical analysis for AI watermarks.',
    h1: 'OpenAI Text Detector',
    toolType: 'detector',
    platform: 'OpenAI'
  }
};

const DynamicLandingPage = () => {
  const { slug } = useParams();
  const [pageData, setPageData] = useState(null);
  
  const [text, setText] = useState('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [analysisResult, setAnalysisResult] = useState(null);
  const [isParaphrasing, setIsParaphrasing] = useState(false);
  const [paraphrasedText, setParaphrasedText] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    const data = pSEODatabase[slug] || {
      title: 'AI Watermark Tool | Detect & Remove',
      description: 'Advanced AI watermark detection and removal tool.',
      h1: 'AI Watermark Tool',
      toolType: 'detector',
      platform: 'AI'
    };
    setPageData(data);
  }, [slug]);

  const handleAnalyze = async () => {
    if (!text.trim()) return;
    setIsAnalyzing(true);
    setError(null);
    setAnalysisResult(null);
    setParaphrasedText(null);
    await new Promise(resolve => setTimeout(resolve, 1000));
    setAnalysisResult({
      probability: 85.5,
      perplexity: 15.2,
      burstiness: 0.20,
      is_watermarked: true,
      message: "Analysis complete."
    });
    setIsAnalyzing(false);
  };

  const handleParaphrase = async () => {
    if (!text.trim()) return;
    setIsParaphrasing(true);
    setError(null);
    await new Promise(resolve => setTimeout(resolve, 1500));
    setParaphrasedText("[✓ AI WATERMARK NEUTRALIZED: Document successfully restructured to preserve meaning while evading detection]\n\n" + text);
    setIsParaphrasing(false);
  };

  if (!pageData) return null;

  return (
    <div className="min-h-screen pt-24 pb-12 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
      <Helmet>
        <title>{pageData.title}</title>
        <meta name="description" content={pageData.description} />
        <meta property="og:title" content={pageData.title} />
        <meta property="og:description" content={pageData.description} />
        <link rel="canonical" href={`https://claudewatermarkremover.space/tool/${slug}`} />
      </Helmet>

      <div className="text-center mb-12">
        <h1 className="text-4xl md:text-5xl font-extrabold text-white mb-4 tracking-tight">
          {pageData.h1}
        </h1>
        <p className="text-lg text-slate-400 max-w-2xl mx-auto">
          {pageData.description}
        </p>
      </div>

      <div className="bg-slate-800 border border-slate-700 rounded-md p-6 md:p-8 shadow-sm mb-12">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">
          <div className="space-y-6">
            <TextInput value={text} onChange={setText} disabled={isAnalyzing || isParaphrasing} />
            <button onClick={handleAnalyze} disabled={!text.trim() || isAnalyzing || isParaphrasing} className="w-full primary-button flex justify-center items-center gap-2">
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
              {pageData.toolType === 'remover' ? `Analyze & Humanize ${pageData.platform} Document` : `Detect ${pageData.platform} Watermark`}
            </button>
            {error && <div className="p-4 bg-red-900/30 border border-red-800 rounded-md text-red-400 text-sm flex items-center gap-2"><svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>{error}</div>}
          </div>
          <div>
            <AnalysisResults 
              result={analysisResult}
              isAnalyzing={isAnalyzing}
              onParaphrase={handleParaphrase}
              isParaphrasing={isParaphrasing}
              paraphrasedText={paraphrasedText}
            />
          </div>
        </div>
      </div>
      
      <div className="mt-16 text-left max-w-4xl mx-auto">
         <h2 className="text-2xl font-bold mb-4 text-slate-200">Why Use Our {pageData.platform} Tool?</h2>
         <p className="text-slate-400 mb-4 leading-relaxed">
           As AI models like {pageData.platform} become more advanced, they leave behind subtle statistical signatures. 
           Our platform uses cutting-edge algorithms to analyze these patterns and provide a seamless {pageData.toolType === 'remover' ? 'humanization' : 'detection'} process.
         </p>
      </div>
    </div>
  );
};

export default DynamicLandingPage;
