import React from 'react';
import { Link } from 'react-router-dom';

export default function HowItWorks() {
  return (
    <div className="py-16 px-4 sm:px-6 lg:px-8 max-w-4xl mx-auto animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="text-center mb-12">
        <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-purple-400 mb-6">
          How Our Claude Watermark Detector Works
        </h1>
        <p className="text-lg text-gray-400">
          Discover the science behind our industry-leading AI detection algorithm.
        </p>
      </div>

      <div className="space-y-12">
        <div className="glass-panel p-8">
          <h2 className="text-2xl font-bold text-gray-200 mb-4">1. Text Ingestion & Parsing</h2>
          <p className="text-gray-400 leading-relaxed">
            When you paste text into our Claude Watermark Remover tool, the first step is normalizing the data. Our system strips out formatting inconsistencies and breaks the text down into measurable tokens and sentence blocks. This ensures that even obfuscated or poorly formatted text can be analyzed accurately by our core engine.
          </p>
        </div>

        <div className="glass-panel p-8">
          <h2 className="text-2xl font-bold text-gray-200 mb-4">2. Statistical Anomaly Detection (Perplexity)</h2>
          <p className="text-gray-400 leading-relaxed mb-4">
            Large Language Models like Claude 3.5 Sonnet operate by predicting the most mathematically probable next word. Our detector reverses this process. By analyzing the "perplexity" of your text, we measure how predictable the word choices are.
          </p>
          <ul className="list-disc list-inside text-gray-400 space-y-2 ml-4">
            <li><strong>Low Perplexity:</strong> The word choices are highly predictable, strongly indicating the text was generated by Claude or ChatGPT.</li>
            <li><strong>High Perplexity:</strong> The text uses creative, unexpected phrasing typical of a human writer.</li>
          </ul>
        </div>

        <div className="glass-panel p-8">
          <h2 className="text-2xl font-bold text-gray-200 mb-4">3. Structural Variance (Burstiness)</h2>
          <p className="text-gray-400 leading-relaxed">
            Human writing is inherently "bursty." We mix long, flowing, complex sentences with short, punchy ones. AI models tend to write with a very consistent rhythm and sentence length. Our engine maps the structural variance of your document. If the sentence lengths are too uniform, the burstiness score drops, flagging the content as AI-generated.
          </p>
        </div>

        <div className="glass-panel p-8">
          <h2 className="text-2xl font-bold text-gray-200 mb-4">4. The Watermark Removal Process</h2>
          <p className="text-gray-400 leading-relaxed">
            Once our detector identifies the specific AI generation patterns (the "watermark"), our restructuring engine takes over. It doesn't just spin synonyms. Instead, it artificially injects human-like burstiness and increases the perplexity of predictable phrases. The result is a completely undetectable document that retains its original meaning but bypasses standard AI detection tools.
          </p>
        </div>
      </div>

      <div className="mt-12 text-center">
        <Link to="/" className="inline-block primary-button text-lg px-8 py-4">
          Try the Detector Now
        </Link>
      </div>
    </div>
  );
}
